appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32ce7cc05bae0700d32b51
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: MXo8LIVvAejUBCUeF4i8cEvbLOAihLdRvx7OP7ZtyDlmg6At8xapHJvbtwVuiOekrDtMzi9qJOI2QHX+bZXpAcAKEvla4ffA1XKkMKnKqoV3JmeN0Anj1cwJdvw3THpotiLHGh3RJm9+qIyENLZe1xETOQb3z2ODHXkT23Fvjwc/r1A2X36/vmIH3LQ7gehXWTjPj4tDSj/sNxyPwvW6N86jwtaYIHZ5MZQqJg/2aZQYh80IjoEcrnz0ACaRGY3DH0MdrY7Dn8C49w/VfvM6vi2MggYKEcLA/ehaeXC8vJ+e6QntnaHkoa75CCNiXtd1QOseYkbOUdvAHulAQqbuv1X08hfRBBck4w8ptgjPgeruut2MPp9Ni+woxR2pFgmpTj83i8CQcDKC70D7ghBNP5LW7SduMFQ30zBUvR3rCcY0MaMBjD9r6x1m2xCNo3v79eZVWWVOnCDuCA71xR6ogdhK/r0piHdMRx5ufR1aj8fMzNuPPAYE5xQuB0blI6Q2WHzlonWjEdduwdlWXSaOUeJUJNmyF4xs5y70lIpQcmIpO4vsyq4WFhCDGwXBNdbDrXYZcjlR95yLvrNwUbSMQkXvwegloDiVx6T0zMMFanjCdgHZS0VV4W+5rJk8+3hT+lzV+N1+xHfSfjjhX4gmDT0mIHy9ws5Je/RFV81ecBM=}
